#pragma once
#include "types.hpp"

/*** 
 * Something interesting to note is that the following nvn functions have been found in nnSdk, however they appear to be for
 * purposes not intended for the user. That being said, I will list them here.
 * nvnCommandBufferCopyTextureToTextureWithCopyEngineNVX
 * nvnTextureGetNvRmSurfaceNVX
 * nvnSyncInitializeFromNvRmSyncNVX
 * nvnMemoryPoolBuilderSetNativeHandleNVX
 * nvnMemoryPoolBuilderGetNativeHandleNVX
 * nvnMemoryPoolGetNativeHandleNVX
 * nvnQueueSetTimeoutNVX
 * nvnCUDAInteropFunction
 * nvnSetGLInteropNVX
 * H3ikr9ix
 * nvnSetExternalDebuggerEnabledNVX
 * nvnMemoryPoolBuilderSetPitchAddressNVX
 * nvnMemoryPoolBuilderGetReservedAddressesNVX
 * nvnDeviceBuilderSetReservedAddressRangesNVX
 * nvnDeviceBuilderGetReservedAddressRangesNVX
 * nvnMemoryPoolBuilderSetBlockLinearAddressNVX
 * nvnMemoryPoolBuilderSetSpecialAddressNVX
 * nvnMemoryPoolGetBlockLinearAddressNVX
 * nvnMemoryPoolGetSpecialAddressNVX
 * nvnSyncGetSyncpointsCountNVX
 * nvnSyncGetSyncpointsNVX
 * nvnSyncSetSyncpointsNVX
 * nvnQueueSetTimesliceNVX
 */

#define NVN_CREATE_PROC(ident, ret, types) \
    typedef ret (*PFNCPP_##ident) types


// Function pointer definitions for all of the NVN functions
// These types may not be exact but they are inferred from the name of the function and usage/strings
namespace nvn {
    NVN_CREATE_PROC(DeviceBuilderSetDefaults, void, (DeviceBuilder*));
    NVN_CREATE_PROC(DeviceBuilderSetFlags, void, (DeviceBuilder*, int));
    NVN_CREATE_PROC(DeviceInitialize, bool, (Device*, const DeviceBuilder*));
    NVN_CREATE_PROC(DeviceFinalize, void, (Device*));
    NVN_CREATE_PROC(DeviceSetDebugLabel, void, (Device*, const char*));
    NVN_CREATE_PROC(DeviceGetProcAddress, GenericFuncPtr, (const Device*, const char*));
    NVN_CREATE_PROC(DeviceGetInteger, void, (const Device*, DeviceInfo::Enum, int*));
    NVN_CREATE_PROC(DeviceGetCurrentTimestampInNanoseconds, uint64_t, (const Device*));
    NVN_CREATE_PROC(DeviceGetTextureHandle, TextureHandle, (const Device*, int, int));
    NVN_CREATE_PROC(DeviceGetTexelFetchHandle, TextureHandle, (const Device*, int));
    NVN_CREATE_PROC(DeviceGetImageHandle, ImageHandle, (const Device*, int));
    NVN_CREATE_PROC(DeviceInstallDebugCallback, void, (Device*, const DebugCallback, void*, bool));
    NVN_CREATE_PROC(DeviceSetWindowOriginMode, void, (Device*, WindowOriginMode::Enum));
    NVN_CREATE_PROC(DeviceSetDepthMode, void, (Device*, DepthMode::Enum));
    NVN_CREATE_PROC(DeviceRegisterFastClearColor, bool, (Device*, const float*, Format::Enum));
    NVN_CREATE_PROC(DeviceRegisterFastClearColori, bool, (Device*, const int*, Format::Enum));
    NVN_CREATE_PROC(DeviceRegisterFastClearColorui, bool, (Device*, const uint32_t*, Format::Enum));
    NVN_CREATE_PROC(DeviceRegisterFastClearDepth, bool, (float, Device*));
    NVN_CREATE_PROC(DeviceGetWindowOriginMode, WindowOriginMode::Enum, (const Device*));
    NVN_CREATE_PROC(DeviceGetDepthMode, DepthMode::Enum, (const Device*));
    NVN_CREATE_PROC(DeviceGetTimestampInNanoseconds, uint64_t, (const Device*, const CounterData*));
    NVN_CREATE_PROC(DeviceApplyDeferredFinalizes, void, (Device*, int));
    NVN_CREATE_PROC(DeviceFinalizeCommandHandle, void, (Device*, CommandHandle));
    NVN_CREATE_PROC(DeviceWaitForError, DeviceWaitForErrorResult::Enum, (const Device*, uint64_t, DeviceErrorData*));
    NVN_CREATE_PROC(QueueGetError, QueueGetErrorResult::Enum, (Queue*, QueueErrorInfo*));
    NVN_CREATE_PROC(QueueBuilderSetDevice, void, (QueueBuilder*, Device*));
    NVN_CREATE_PROC(QueueBuilderSetDefaults, void, (QueueBuilder*));
    NVN_CREATE_PROC(QueueBuilderSetFlags, void, (QueueBuilder*, int));
    NVN_CREATE_PROC(QueueBuilderSetCommandMemorySize, void, (QueueBuilder*, size_t));
    NVN_CREATE_PROC(QueueBuilderSetComputeMemorySize, void, (QueueBuilder*, size_t));
    NVN_CREATE_PROC(QueueBuilderGetQueueMemorySize, size_t, (const QueueBuilder*));
    NVN_CREATE_PROC(QueueBuilderSetQueueMemory, void, (QueueBuilder*, void*, size_t));
    NVN_CREATE_PROC(QueueBuilderSetCommandFlushThreshold, void, (QueueBuilder*, size_t));
    NVN_CREATE_PROC(QueueInitialize, bool, (Queue*, const QueueBuilder*));
    NVN_CREATE_PROC(QueueFinalize, void, (Queue*));
    NVN_CREATE_PROC(QueueSetDebugLabel, void, (Queue*, const char*));
    NVN_CREATE_PROC(QueueSubmitCommands, void, (Queue*, int, const CommandHandle*));
    NVN_CREATE_PROC(QueueFlush, void, (Queue*));
    NVN_CREATE_PROC(QueueFinish, void, (Queue*));
    NVN_CREATE_PROC(QueuePresentTexture, void, (Queue*, Window*, int));
    NVN_CREATE_PROC(QueueAcquireTexture, QueueAcquireTextureResult::Enum, (Queue*, Window*, int*));
    NVN_CREATE_PROC(WindowBuilderSetDevice, void, (WindowBuilder*, Device*));
    NVN_CREATE_PROC(WindowBuilderSetDefaults, void, (WindowBuilder*));
    NVN_CREATE_PROC(WindowBuilderSetNativeWindow, void, (WindowBuilder*, NativeWindow));
    NVN_CREATE_PROC(WindowBuilderSetTextures, void, (WindowBuilder*, int, Texture* const*));
    NVN_CREATE_PROC(WindowBuilderSetPresentInterval, void, (WindowBuilder*, int));
    NVN_CREATE_PROC(WindowBuilderGetNativeWindow, NativeWindow, (const WindowBuilder*));
    NVN_CREATE_PROC(WindowBuilderGetPresentInterval, int, (const WindowBuilder*));
    NVN_CREATE_PROC(WindowInitialize, bool, (Window*, const WindowBuilder*));
    NVN_CREATE_PROC(WindowFinalize, void, (Window*));
    NVN_CREATE_PROC(WindowSetDebugLabel, void, (Window*, const char*));
    NVN_CREATE_PROC(WindowAcquireTexture, WindowAcquireTextureResult::Enum, (Window*, Sync*, int*));
    NVN_CREATE_PROC(WindowGetNativeWindow, NativeWindow, (const Window*));
    NVN_CREATE_PROC(WindowGetPresentInterval, int, (const Window*));
    NVN_CREATE_PROC(WindowSetPresentInterval, void, (Window*, int));
    NVN_CREATE_PROC(WindowSetCrop, void, (Window*, int, int, int, int));
    NVN_CREATE_PROC(ProgramInitialize, bool, (Program*, Device*));
    NVN_CREATE_PROC(ProgramFinalize, void, (Program*));
    NVN_CREATE_PROC(ProgramSetDebugLabel, void, (Program*, const char*));
    NVN_CREATE_PROC(ProgramSetShaders, bool, (Program*, int, const ShaderData*));
    NVN_CREATE_PROC(MemoryPoolBuilderSetDevice, void, (MemoryPoolBuilder*, Device*));
    NVN_CREATE_PROC(MemoryPoolBuilderSetDefaults, void, (MemoryPoolBuilder*));
    NVN_CREATE_PROC(MemoryPoolBuilderSetStorage, void, (MemoryPoolBuilder*, void*, size_t));
    NVN_CREATE_PROC(MemoryPoolBuilderSetFlags, void, (MemoryPoolBuilder*, int));
    NVN_CREATE_PROC(MemoryPoolBuilderGetMemory, void*, (const MemoryPoolBuilder*));
    NVN_CREATE_PROC(MemoryPoolBuilderGetSize, size_t, (const MemoryPoolBuilder*));
    NVN_CREATE_PROC(MemoryPoolBuilderGetFlags, int, (const MemoryPoolBuilder*));
    NVN_CREATE_PROC(MemoryPoolInitialize, bool, (MemoryPool*, const MemoryPoolBuilder*));
    NVN_CREATE_PROC(MemoryPoolSetDebugLabel, void, (MemoryPool*, const char*));
    NVN_CREATE_PROC(MemoryPoolFinalize, void, (MemoryPool*));
    NVN_CREATE_PROC(MemoryPoolMap, void*, (const MemoryPool*));
    NVN_CREATE_PROC(MemoryPoolFlushMappedRange, void, (const MemoryPool*, ptrdiff_t, size_t));
    NVN_CREATE_PROC(MemoryPoolInvalidateMappedRange, void, (const MemoryPool*, ptrdiff_t, size_t));
    NVN_CREATE_PROC(MemoryPoolGetBufferAddress, BufferAddress, (const MemoryPool*));
    NVN_CREATE_PROC(MemoryPoolMapVirtual, bool, (MemoryPool*, int, const MappingRequest*));
    NVN_CREATE_PROC(MemoryPoolGetSize, size_t, (const MemoryPool*));
    NVN_CREATE_PROC(MemoryPoolGetFlags, int, (const MemoryPool*));
    NVN_CREATE_PROC(TexturePoolInitialize, bool, (TexturePool*, const MemoryPool*, ptrdiff_t, int));
    NVN_CREATE_PROC(TexturePoolSetDebugLabel, void, (TexturePool*, const char*));
    NVN_CREATE_PROC(TexturePoolFinalize, void, (TexturePool*));
    NVN_CREATE_PROC(TexturePoolRegisterTexture, void, (const TexturePool*, int, const Texture*, const TextureView*));
    NVN_CREATE_PROC(TexturePoolRegisterImage, void, (const TexturePool*, int, const Texture*, const TextureView*));
    NVN_CREATE_PROC(TexturePoolGetMemoryPool, const MemoryPool* , (const TexturePool*));
    NVN_CREATE_PROC(TexturePoolGetMemoryOffset, ptrdiff_t, (const TexturePool*));
    NVN_CREATE_PROC(TexturePoolGetSize, int, (const TexturePool*));
    NVN_CREATE_PROC(SamplerPoolInitialize, bool, (SamplerPool*, const MemoryPool*, ptrdiff_t, int));
    NVN_CREATE_PROC(SamplerPoolSetDebugLabel, void, (SamplerPool*, const char*));
    NVN_CREATE_PROC(SamplerPoolFinalize, void, (SamplerPool*));
    NVN_CREATE_PROC(SamplerPoolRegisterSampler, void, (const SamplerPool*, int, const Sampler*));
    NVN_CREATE_PROC(SamplerPoolGetMemoryPool, const MemoryPool* , (const SamplerPool*));
    NVN_CREATE_PROC(SamplerPoolGetMemoryOffset, ptrdiff_t, (const SamplerPool*));
    NVN_CREATE_PROC(SamplerPoolGetSize, int, (const SamplerPool*));
    NVN_CREATE_PROC(BufferBuilderSetDevice, void, (BufferBuilder*, Device*));
    NVN_CREATE_PROC(BufferBuilderSetDefaults, void, (BufferBuilder*));
    NVN_CREATE_PROC(BufferBuilderSetStorage, void, (BufferBuilder*, MemoryPool*, ptrdiff_t, size_t));
    NVN_CREATE_PROC(BufferBuilderGetMemoryPool, MemoryPool* , (const BufferBuilder*));
    NVN_CREATE_PROC(BufferBuilderGetMemoryOffset, ptrdiff_t, (const BufferBuilder*));
    NVN_CREATE_PROC(BufferBuilderGetSize, size_t, (const BufferBuilder*));
    NVN_CREATE_PROC(BufferInitialize, bool, (Buffer*, const BufferBuilder*));
    NVN_CREATE_PROC(BufferSetDebugLabel, void, (Buffer*, const char*));
    NVN_CREATE_PROC(BufferFinalize, void, (Buffer*));
    NVN_CREATE_PROC(BufferMap, void*, (const Buffer*));
    NVN_CREATE_PROC(BufferGetAddress, BufferAddress, (const Buffer*));
    NVN_CREATE_PROC(BufferFlushMappedRange, void, (const Buffer*, ptrdiff_t, size_t));
    NVN_CREATE_PROC(BufferInvalidateMappedRange, void, (const Buffer*, ptrdiff_t, size_t));
    NVN_CREATE_PROC(BufferGetMemoryPool, MemoryPool* , (const Buffer*));
    NVN_CREATE_PROC(BufferGetMemoryOffset, ptrdiff_t, (const Buffer*));
    NVN_CREATE_PROC(BufferGetSize, size_t, (const Buffer*));
    NVN_CREATE_PROC(BufferGetDebugID, uint64_t, (const Buffer*));
    NVN_CREATE_PROC(TextureBuilderSetDevice, void, (TextureBuilder*, Device*));
    NVN_CREATE_PROC(TextureBuilderSetDefaults, void, (TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderSetFlags, void, (TextureBuilder*, int));
    NVN_CREATE_PROC(TextureBuilderSetTarget, void, (TextureBuilder*, TextureTarget::Enum));
    NVN_CREATE_PROC(TextureBuilderSetWidth, void, (TextureBuilder*, int));
    NVN_CREATE_PROC(TextureBuilderSetHeight, void, (TextureBuilder*, int));
    NVN_CREATE_PROC(TextureBuilderSetDepth, void, (TextureBuilder*, int));
    NVN_CREATE_PROC(TextureBuilderSetSize1D, void, (TextureBuilder*, int));
    NVN_CREATE_PROC(TextureBuilderSetSize2D, void, (TextureBuilder*, int, int));
    NVN_CREATE_PROC(TextureBuilderSetSize3D, void, (TextureBuilder*, int, int, int));
    NVN_CREATE_PROC(TextureBuilderSetLevels, void, (TextureBuilder*, int));
    NVN_CREATE_PROC(TextureBuilderSetFormat, void, (TextureBuilder*, Format::Enum));
    NVN_CREATE_PROC(TextureBuilderSetSamples, void, (TextureBuilder*, int));
    NVN_CREATE_PROC(TextureBuilderSetSwizzle, void, (TextureBuilder*, TextureSwizzle::Enum, TextureSwizzle::Enum, TextureSwizzle::Enum, TextureSwizzle::Enum));
    NVN_CREATE_PROC(TextureBuilderSetDepthStencilMode, void, (TextureBuilder*, TextureDepthStencilMode::Enum));
    NVN_CREATE_PROC(TextureBuilderGetStorageSize, size_t, (const TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderGetStorageAlignment, size_t, (const TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderSetStorage, void, (TextureBuilder*, MemoryPool*, ptrdiff_t));
    NVN_CREATE_PROC(TextureBuilderSetPackagedTextureData, void, (TextureBuilder*, const void*));
    NVN_CREATE_PROC(TextureBuilderSetPackagedTextureLayout, void, (TextureBuilder*, const PackagedTextureLayout*));
    NVN_CREATE_PROC(TextureBuilderSetStride, void, (TextureBuilder*, ptrdiff_t));
    NVN_CREATE_PROC(TextureBuilderSetGLTextureName, void, (TextureBuilder*, uint32_t));
    NVN_CREATE_PROC(TextureBuilderGetStorageClass, StorageClass, (const TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderGetFlags, int, (const TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderGetTarget, TextureTarget::Enum, (const TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderGetWidth, int, (const TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderGetHeight, int, (const TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderGetDepth, int, (const TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderGetLevels, int, (const TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderGetFormat, Format::Enum, (const TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderGetSamples, int, (const TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderGetSwizzle, void, (const TextureBuilder*, TextureSwizzle*, TextureSwizzle*, TextureSwizzle*, TextureSwizzle*));
    NVN_CREATE_PROC(TextureBuilderGetDepthStencilMode, TextureDepthStencilMode::Enum, (const TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderGetPackagedTextureData, const void* , (const TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderGetStride, ptrdiff_t, (const TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderGetSparseTileLayout, void, (const TextureBuilder*, TextureSparseTileLayout*));
    NVN_CREATE_PROC(TextureBuilderGetGLTextureName, uint32_t, (const TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderGetZCullStorageSize, size_t, (const TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderGetMemoryPool, MemoryPool* , (const TextureBuilder*));
    NVN_CREATE_PROC(TextureBuilderGetMemoryOffset, ptrdiff_t, (const TextureBuilder*));
    NVN_CREATE_PROC(TextureViewSetDefaults, void, (TextureView*));
    NVN_CREATE_PROC(TextureViewSetLevels, void, (TextureView*, int, int));
    NVN_CREATE_PROC(TextureViewSetLayers, void, (TextureView*, int, int));
    NVN_CREATE_PROC(TextureViewSetFormat, void, (TextureView*, Format::Enum));
    NVN_CREATE_PROC(TextureViewSetSwizzle, void, (TextureView*, TextureSwizzle::Enum, TextureSwizzle::Enum, TextureSwizzle::Enum, TextureSwizzle::Enum));
    NVN_CREATE_PROC(TextureViewSetDepthStencilMode, void, (TextureView*, TextureDepthStencilMode::Enum));
    NVN_CREATE_PROC(TextureViewSetTarget, void, (TextureView*, TextureTarget::Enum));
    NVN_CREATE_PROC(TextureViewGetLevels, bool, (const TextureView*, int*, int*));
    NVN_CREATE_PROC(TextureViewGetLayers, bool, (const TextureView*, int*, int*));
    NVN_CREATE_PROC(TextureViewGetFormat, bool, (const TextureView*, Format*));
    NVN_CREATE_PROC(TextureViewGetSwizzle, bool, (const TextureView*, TextureSwizzle*, TextureSwizzle*, TextureSwizzle*, TextureSwizzle*));
    NVN_CREATE_PROC(TextureViewGetDepthStencilMode, bool, (const TextureView*, TextureDepthStencilMode*));
    NVN_CREATE_PROC(TextureViewGetTarget, bool, (const TextureView*, TextureTarget*));
    NVN_CREATE_PROC(TextureViewCompare, bool, (const TextureView*, const TextureView*));
    NVN_CREATE_PROC(TextureInitialize, bool, (Texture*, const TextureBuilder*));
    NVN_CREATE_PROC(TextureGetZCullStorageSize, size_t, (const Texture*));
    NVN_CREATE_PROC(TextureFinalize, void, (Texture*));
    NVN_CREATE_PROC(TextureSetDebugLabel, void, (Texture*, const char*));
    NVN_CREATE_PROC(TextureGetStorageClass, StorageClass, (const Texture*));
    NVN_CREATE_PROC(TextureGetViewOffset, ptrdiff_t, (const Texture*, const TextureView*));
    NVN_CREATE_PROC(TextureGetFlags, int, (const Texture*));
    NVN_CREATE_PROC(TextureGetTarget, TextureTarget::Enum, (const Texture*));
    NVN_CREATE_PROC(TextureGetWidth, int, (const Texture*));
    NVN_CREATE_PROC(TextureGetHeight, int, (const Texture*));
    NVN_CREATE_PROC(TextureGetDepth, int, (const Texture*));
    NVN_CREATE_PROC(TextureGetLevels, int, (const Texture*));
    NVN_CREATE_PROC(TextureGetFormat, Format::Enum, (const Texture*));
    NVN_CREATE_PROC(TextureGetSamples, int, (const Texture*));
    NVN_CREATE_PROC(TextureGetSwizzle, void, (const Texture*, TextureSwizzle*, TextureSwizzle*, TextureSwizzle*, TextureSwizzle*));
    NVN_CREATE_PROC(TextureGetDepthStencilMode, TextureDepthStencilMode::Enum, (const Texture*));
    NVN_CREATE_PROC(TextureGetStride, ptrdiff_t, (const Texture*));
    NVN_CREATE_PROC(TextureGetTextureAddress, TextureAddress, (const Texture*));
    NVN_CREATE_PROC(TextureGetSparseTileLayout, void, (const Texture*, TextureSparseTileLayout*));
    NVN_CREATE_PROC(TextureWriteTexels, void, (const Texture*, const TextureView*, const CopyRegion*, const void*));
    NVN_CREATE_PROC(TextureReadTexels, void, (const Texture*, const TextureView*, const CopyRegion*, void*));
    NVN_CREATE_PROC(TextureFlushTexels, void, (const Texture*, const TextureView*, const CopyRegion*));
    NVN_CREATE_PROC(TextureInvalidateTexels, void, (const Texture*, const TextureView*, const CopyRegion*));
    NVN_CREATE_PROC(TextureGetMemoryPool, MemoryPool* , (const Texture*));
    NVN_CREATE_PROC(TextureGetMemoryOffset, ptrdiff_t, (const Texture*));
    NVN_CREATE_PROC(TextureGetStorageSize, int, (const Texture*));
    NVN_CREATE_PROC(TextureCompare, bool, (const Texture*, const Texture*));
    NVN_CREATE_PROC(TextureGetDebugID, uint64_t, (const Texture*));
    NVN_CREATE_PROC(SamplerBuilderSetDevice, void, (SamplerBuilder*, Device*));
    NVN_CREATE_PROC(SamplerBuilderSetDefaults, void, (SamplerBuilder*));
    NVN_CREATE_PROC(SamplerBuilderSetMinMagFilter, void, (SamplerBuilder*, MinFilter::Enum, MagFilter::Enum));
    NVN_CREATE_PROC(SamplerBuilderSetWrapMode, void, (SamplerBuilder*, WrapMode::Enum, WrapMode::Enum, WrapMode::Enum));
    NVN_CREATE_PROC(SamplerBuilderSetLodClamp, void, (SamplerBuilder*, float, float));
    NVN_CREATE_PROC(SamplerBuilderSetLodBias, void, (SamplerBuilder*, float));
    NVN_CREATE_PROC(SamplerBuilderSetCompare, void, (SamplerBuilder*, CompareMode::Enum, CompareFunc::Enum));
    NVN_CREATE_PROC(SamplerBuilderSetBorderColor, void, (SamplerBuilder*, const float*));
    NVN_CREATE_PROC(SamplerBuilderSetBorderColori, void, (SamplerBuilder*, const int*));
    NVN_CREATE_PROC(SamplerBuilderSetBorderColorui, void, (SamplerBuilder*, const uint32_t*));
    NVN_CREATE_PROC(SamplerBuilderSetMaxAnisotropy, void, (SamplerBuilder*, float));
    NVN_CREATE_PROC(SamplerBuilderSetReductionFilter, void, (SamplerBuilder*, SamplerReduction::Enum));
    NVN_CREATE_PROC(SamplerBuilderGetMinMagFilter, void, (const SamplerBuilder*, MinFilter*, MagFilter*));
    NVN_CREATE_PROC(SamplerBuilderGetWrapMode, void, (const SamplerBuilder*, WrapMode*, WrapMode*, WrapMode*));
    NVN_CREATE_PROC(SamplerBuilderGetLodClamp, void, (const SamplerBuilder*, float*, float*));
    NVN_CREATE_PROC(SamplerBuilderGetLodBias, float, (const SamplerBuilder*));
    NVN_CREATE_PROC(SamplerBuilderGetCompare, void, (const SamplerBuilder*, CompareMode*, CompareFunc*));
    NVN_CREATE_PROC(SamplerBuilderGetBorderColor, void, (const SamplerBuilder*, float*));
    NVN_CREATE_PROC(SamplerBuilderGetBorderColori, void, (const SamplerBuilder*, int*));
    NVN_CREATE_PROC(SamplerBuilderGetBorderColorui, void, (const SamplerBuilder*, uint32_t*));
    NVN_CREATE_PROC(SamplerBuilderGetMaxAnisotropy, float, (const SamplerBuilder*));
    NVN_CREATE_PROC(SamplerBuilderGetReductionFilter, SamplerReduction::Enum, (const SamplerBuilder*));
    NVN_CREATE_PROC(SamplerInitialize, bool, (Sampler*, const SamplerBuilder*));
    NVN_CREATE_PROC(SamplerFinalize, void, (Sampler*));
    NVN_CREATE_PROC(SamplerSetDebugLabel, void, (Sampler*, const char*));
    NVN_CREATE_PROC(SamplerGetMinMagFilter, void, (const Sampler*, MinFilter*, MagFilter*));
    NVN_CREATE_PROC(SamplerGetWrapMode, void, (const Sampler*, WrapMode*, WrapMode*, WrapMode*));
    NVN_CREATE_PROC(SamplerGetLodClamp, void, (const Sampler*, float*, float*));
    NVN_CREATE_PROC(SamplerGetLodBias, float, (const Sampler*));
    NVN_CREATE_PROC(SamplerGetCompare, void, (const Sampler*, CompareMode*, CompareFunc*));
    NVN_CREATE_PROC(SamplerGetBorderColor, void, (const Sampler*, float*));
    NVN_CREATE_PROC(SamplerGetBorderColori, void, (const Sampler*, int*));
    NVN_CREATE_PROC(SamplerGetBorderColorui, void, (const Sampler*, uint32_t*));
    NVN_CREATE_PROC(SamplerGetMaxAnisotropy, float, (const Sampler*));
    NVN_CREATE_PROC(SamplerGetReductionFilter, SamplerReduction::Enum, (const Sampler*));
    NVN_CREATE_PROC(SamplerCompare, bool, (const Sampler*, const Sampler*));
    NVN_CREATE_PROC(SamplerGetDebugID, uint64_t, (const Sampler*));
    NVN_CREATE_PROC(BlendStateSetDefaults, void, (BlendState*));
    NVN_CREATE_PROC(BlendStateSetBlendTarget, void, (BlendState*, int));
    NVN_CREATE_PROC(BlendStateSetBlendFunc, void, (BlendState*, BlendFunc::Enum, BlendFunc::Enum, BlendFunc::Enum, BlendFunc::Enum));
    NVN_CREATE_PROC(BlendStateSetBlendEquation, void, (BlendState*, BlendEquation::Enum, BlendEquation::Enum));
    NVN_CREATE_PROC(BlendStateSetAdvancedMode, void, (BlendState*, BlendAdvancedMode::Enum));
    NVN_CREATE_PROC(BlendStateSetAdvancedOverlap, void, (BlendState*, BlendAdvancedOverlap::Enum));
    NVN_CREATE_PROC(BlendStateSetAdvancedPremultipliedSrc, void, (BlendState*, bool));
    NVN_CREATE_PROC(BlendStateSetAdvancedNormalizedDst, void, (BlendState*, bool));
    NVN_CREATE_PROC(BlendStateGetBlendTarget, int, (const BlendState*));
    NVN_CREATE_PROC(BlendStateGetBlendFunc, void, (const BlendState*, BlendFunc*, BlendFunc*, BlendFunc*, BlendFunc*));
    NVN_CREATE_PROC(BlendStateGetBlendEquation, void, (const BlendState*, BlendEquation*, BlendEquation*));
    NVN_CREATE_PROC(BlendStateGetAdvancedMode, BlendAdvancedMode::Enum, (const BlendState*));
    NVN_CREATE_PROC(BlendStateGetAdvancedOverlap, BlendAdvancedOverlap::Enum, (const BlendState*));
    NVN_CREATE_PROC(BlendStateGetAdvancedPremultipliedSrc, bool, (const BlendState*));
    NVN_CREATE_PROC(BlendStateGetAdvancedNormalizedDst, bool, (const BlendState*));
    NVN_CREATE_PROC(ColorStateSetDefaults, void, (ColorState*));
    NVN_CREATE_PROC(ColorStateSetBlendEnable, void, (ColorState*, int, bool));
    NVN_CREATE_PROC(ColorStateSetLogicOp, void, (ColorState*, LogicOp::Enum));
    NVN_CREATE_PROC(ColorStateSetAlphaTest, void, (ColorState*, AlphaFunc::Enum));
    NVN_CREATE_PROC(ColorStateGetBlendEnable, bool, (const ColorState*, int));
    NVN_CREATE_PROC(ColorStateGetLogicOp, LogicOp::Enum, (const ColorState*));
    NVN_CREATE_PROC(ColorStateGetAlphaTest, AlphaFunc::Enum, (const ColorState*));
    NVN_CREATE_PROC(ChannelMaskStateSetDefaults, void, (ChannelMaskState*));
    NVN_CREATE_PROC(ChannelMaskStateSetChannelMask, void, (ChannelMaskState*, int, bool, bool, bool, bool));
    NVN_CREATE_PROC(ChannelMaskStateGetChannelMask, void, (const ChannelMaskState*, int, bool*, bool*, bool*, bool*));
    NVN_CREATE_PROC(MultisampleStateSetDefaults, void, (MultisampleState*));
    NVN_CREATE_PROC(MultisampleStateSetMultisampleEnable, void, (MultisampleState*, bool));
    NVN_CREATE_PROC(MultisampleStateSetSamples, void, (MultisampleState*, int));
    NVN_CREATE_PROC(MultisampleStateSetAlphaToCoverageEnable, void, (MultisampleState*, bool));
    NVN_CREATE_PROC(MultisampleStateSetAlphaToCoverageDither, void, (MultisampleState*, bool));
    NVN_CREATE_PROC(MultisampleStateGetMultisampleEnable, bool, (const MultisampleState*));
    NVN_CREATE_PROC(MultisampleStateGetSamples, int, (const MultisampleState*));
    NVN_CREATE_PROC(MultisampleStateGetAlphaToCoverageEnable, bool, (const MultisampleState*));
    NVN_CREATE_PROC(MultisampleStateGetAlphaToCoverageDither, bool, (const MultisampleState*));
    NVN_CREATE_PROC(MultisampleStateSetRasterSamples, void, (MultisampleState*, int));
    NVN_CREATE_PROC(MultisampleStateGetRasterSamples, int, (MultisampleState*));
    NVN_CREATE_PROC(MultisampleStateSetCoverageModulationMode, void, (MultisampleState*, CoverageModulationMode::Enum));
    NVN_CREATE_PROC(MultisampleStateGetCoverageModulationMode, CoverageModulationMode::Enum, (const MultisampleState*));
    NVN_CREATE_PROC(MultisampleStateSetCoverageToColorEnable, void, (MultisampleState*, bool));
    NVN_CREATE_PROC(MultisampleStateGetCoverageToColorEnable, bool, (const MultisampleState*));
    NVN_CREATE_PROC(MultisampleStateSetCoverageToColorOutput, void, (MultisampleState*, int));
    NVN_CREATE_PROC(MultisampleStateGetCoverageToColorOutput, int, (const MultisampleState*));
    NVN_CREATE_PROC(MultisampleStateSetSampleLocationsEnable, void, (MultisampleState*, bool));
    NVN_CREATE_PROC(MultisampleStateGetSampleLocationsEnable, bool, (const MultisampleState*));
    NVN_CREATE_PROC(MultisampleStateGetSampleLocationsGrid, void, (MultisampleState*, int*, int*));
    NVN_CREATE_PROC(MultisampleStateSetSampleLocationsGridEnable, void, (MultisampleState*, bool));
    NVN_CREATE_PROC(MultisampleStateGetSampleLocationsGridEnable, bool, (const MultisampleState*));
    NVN_CREATE_PROC(MultisampleStateSetSampleLocations, void, (MultisampleState*, int, int, const float*));
    NVN_CREATE_PROC(PolygonStateSetDefaults, void, (PolygonState*));
    NVN_CREATE_PROC(PolygonStateSetCullFace, void, (PolygonState*, Face::Enum));
    NVN_CREATE_PROC(PolygonStateSetFrontFace, void, (PolygonState*, FrontFace::Enum));
    NVN_CREATE_PROC(PolygonStateSetPolygonMode, void, (PolygonState*, PolygonMode::Enum));
    NVN_CREATE_PROC(PolygonStateSetPolygonOffsetEnables, void, (PolygonState*, int));
    NVN_CREATE_PROC(PolygonStateGetCullFace, Face::Enum, (const PolygonState*));
    NVN_CREATE_PROC(PolygonStateGetFrontFace, FrontFace::Enum, (const PolygonState*));
    NVN_CREATE_PROC(PolygonStateGetPolygonMode, PolygonMode::Enum, (const PolygonState*));
    NVN_CREATE_PROC(PolygonStateGetPolygonOffsetEnables, int, (const PolygonState*));
    NVN_CREATE_PROC(DepthStencilStateSetDefaults, void, (DepthStencilState*));
    NVN_CREATE_PROC(DepthStencilStateSetDepthTestEnable, void, (DepthStencilState*, bool));
    NVN_CREATE_PROC(DepthStencilStateSetDepthWriteEnable, void, (DepthStencilState*, bool));
    NVN_CREATE_PROC(DepthStencilStateSetDepthFunc, void, (DepthStencilState*, DepthFunc::Enum));
    NVN_CREATE_PROC(DepthStencilStateSetStencilTestEnable, void, (DepthStencilState*, bool));
    NVN_CREATE_PROC(DepthStencilStateSetStencilFunc, void, (DepthStencilState*, Face::Enum, StencilFunc::Enum));
    NVN_CREATE_PROC(DepthStencilStateSetStencilOp, void, (DepthStencilState*, Face::Enum, StencilOp::Enum, StencilOp::Enum, StencilOp::Enum));
    NVN_CREATE_PROC(DepthStencilStateGetDepthTestEnable, bool, (const DepthStencilState*));
    NVN_CREATE_PROC(DepthStencilStateGetDepthWriteEnable, bool, (const DepthStencilState*));
    NVN_CREATE_PROC(DepthStencilStateGetDepthFunc, DepthFunc::Enum, (const DepthStencilState*));
    NVN_CREATE_PROC(DepthStencilStateGetStencilTestEnable, bool, (const DepthStencilState*));
    NVN_CREATE_PROC(DepthStencilStateGetStencilFunc, StencilFunc::Enum, (const DepthStencilState*, Face::Enum));
    NVN_CREATE_PROC(DepthStencilStateGetStencilOp, void, (const DepthStencilState*, Face::Enum, StencilOp*, StencilOp*, StencilOp*));
    NVN_CREATE_PROC(VertexAttribStateSetDefaults, void, (VertexAttribState*));
    NVN_CREATE_PROC(VertexAttribStateSetFormat, void, (VertexAttribState*, Format::Enum, ptrdiff_t));
    NVN_CREATE_PROC(VertexAttribStateSetStreamIndex, void, (VertexAttribState*, int));
    NVN_CREATE_PROC(VertexAttribStateGetFormat, void, (const VertexAttribState*, Format*, ptrdiff_t*));
    NVN_CREATE_PROC(VertexAttribStateGetStreamIndex, int, (const VertexAttribState*));
    NVN_CREATE_PROC(VertexStreamStateSetDefaults, void, (VertexStreamState*));
    NVN_CREATE_PROC(VertexStreamStateSetStride, void, (VertexStreamState*, ptrdiff_t));
    NVN_CREATE_PROC(VertexStreamStateSetDivisor, void, (VertexStreamState*, int));
    NVN_CREATE_PROC(VertexStreamStateGetStride, ptrdiff_t, (const VertexStreamState*));
    NVN_CREATE_PROC(VertexStreamStateGetDivisor, int, (const VertexStreamState*));
    NVN_CREATE_PROC(CommandBufferInitialize, bool, (CommandBuffer*, Device*));
    NVN_CREATE_PROC(CommandBufferFinalize, void, (CommandBuffer*));
    NVN_CREATE_PROC(CommandBufferSetDebugLabel, void, (CommandBuffer*, const char*));
    NVN_CREATE_PROC(CommandBufferSetMemoryCallback, void, (CommandBuffer*, CommandBufferMemoryCallback));
    NVN_CREATE_PROC(CommandBufferSetMemoryCallbackData, void, (CommandBuffer*, void*));
    NVN_CREATE_PROC(CommandBufferAddCommandMemory, void, (CommandBuffer*, const MemoryPool*, ptrdiff_t, size_t));
    NVN_CREATE_PROC(CommandBufferAddControlMemory, void, (CommandBuffer*, void*, size_t));
    NVN_CREATE_PROC(CommandBufferGetCommandMemorySize, size_t, (const CommandBuffer*));
    NVN_CREATE_PROC(CommandBufferGetCommandMemoryUsed, size_t, (const CommandBuffer*));
    NVN_CREATE_PROC(CommandBufferGetCommandMemoryFree, size_t, (const CommandBuffer*));
    NVN_CREATE_PROC(CommandBufferGetControlMemorySize, size_t, (const CommandBuffer*));
    NVN_CREATE_PROC(CommandBufferGetControlMemoryUsed, size_t, (const CommandBuffer*));
    NVN_CREATE_PROC(CommandBufferGetControlMemoryFree, size_t, (const CommandBuffer*));
    NVN_CREATE_PROC(CommandBufferBeginRecording, void, (CommandBuffer*));
    NVN_CREATE_PROC(CommandBufferEndRecording, CommandHandle, (CommandBuffer*));
    NVN_CREATE_PROC(CommandBufferCallCommands, void, (CommandBuffer*, int, const CommandHandle*));
    NVN_CREATE_PROC(CommandBufferCopyCommands, void, (CommandBuffer*, int, const CommandHandle*));
    NVN_CREATE_PROC(CommandBufferBindBlendState, void, (CommandBuffer*, const BlendState*));
    NVN_CREATE_PROC(CommandBufferBindChannelMaskState, void, (CommandBuffer*, const ChannelMaskState*));
    NVN_CREATE_PROC(CommandBufferBindColorState, void, (CommandBuffer*, const ColorState*));
    NVN_CREATE_PROC(CommandBufferBindMultisampleState, void, (CommandBuffer*, const MultisampleState*));
    NVN_CREATE_PROC(CommandBufferBindPolygonState, void, (CommandBuffer*, const PolygonState*));
    NVN_CREATE_PROC(CommandBufferBindDepthStencilState, void, (CommandBuffer*, const DepthStencilState*));
    NVN_CREATE_PROC(CommandBufferBindVertexAttribState, void, (CommandBuffer*, int, const VertexAttribState*));
    NVN_CREATE_PROC(CommandBufferBindVertexStreamState, void, (CommandBuffer*, int, const VertexStreamState*));
    NVN_CREATE_PROC(CommandBufferBindProgram, void, (CommandBuffer*, const Program*, int));
    NVN_CREATE_PROC(CommandBufferBindVertexBuffer, void, (CommandBuffer*, int, BufferAddress, size_t));
    NVN_CREATE_PROC(CommandBufferBindVertexBuffers, void, (CommandBuffer*, int, int, const BufferRange*));
    NVN_CREATE_PROC(CommandBufferBindUniformBuffer, void, (CommandBuffer*, ShaderStage::Enum, int, BufferAddress, size_t));
    NVN_CREATE_PROC(CommandBufferBindUniformBuffers, void, (CommandBuffer*, ShaderStage::Enum, int, int, const BufferRange*));
    NVN_CREATE_PROC(CommandBufferBindTransformFeedbackBuffer, void, (CommandBuffer*, int, BufferAddress, size_t));
    NVN_CREATE_PROC(CommandBufferBindTransformFeedbackBuffers, void, (CommandBuffer*, int, int, const BufferRange*));
    NVN_CREATE_PROC(CommandBufferBindStorageBuffer, void, (CommandBuffer*, ShaderStage::Enum, int, BufferAddress, size_t));
    NVN_CREATE_PROC(CommandBufferBindStorageBuffers, void, (CommandBuffer*, ShaderStage::Enum, int, int, const BufferRange*));
    NVN_CREATE_PROC(CommandBufferBindTexture, void, (CommandBuffer*, ShaderStage::Enum, int, TextureHandle));
    NVN_CREATE_PROC(CommandBufferBindTextures, void, (CommandBuffer*, ShaderStage::Enum, int, int, const TextureHandle*));
    NVN_CREATE_PROC(CommandBufferBindImage, void, (CommandBuffer*, ShaderStage::Enum, int, ImageHandle));
    NVN_CREATE_PROC(CommandBufferBindImages, void, (CommandBuffer*, ShaderStage::Enum, int, int, const ImageHandle*));
    NVN_CREATE_PROC(CommandBufferSetPatchSize, void, (CommandBuffer*, int));
    NVN_CREATE_PROC(CommandBufferSetInnerTessellationLevels, void, (CommandBuffer*, const float*));
    NVN_CREATE_PROC(CommandBufferSetOuterTessellationLevels, void, (CommandBuffer*, const float*));
    NVN_CREATE_PROC(CommandBufferSetPrimitiveRestart, void, (CommandBuffer*, bool, int));
    NVN_CREATE_PROC(CommandBufferBeginTransformFeedback, void, (CommandBuffer*, BufferAddress));
    NVN_CREATE_PROC(CommandBufferEndTransformFeedback, void, (CommandBuffer*, BufferAddress));
    NVN_CREATE_PROC(CommandBufferPauseTransformFeedback, void, (CommandBuffer*, BufferAddress));
    NVN_CREATE_PROC(CommandBufferResumeTransformFeedback, void, (CommandBuffer*, BufferAddress));
    NVN_CREATE_PROC(CommandBufferDrawTransformFeedback, void, (CommandBuffer*, DrawPrimitive::Enum, BufferAddress));
    NVN_CREATE_PROC(CommandBufferDrawArrays, void, (CommandBuffer*, DrawPrimitive::Enum, int, int));
    NVN_CREATE_PROC(CommandBufferDrawElements, void, (CommandBuffer*, DrawPrimitive::Enum, IndexType::Enum, int, BufferAddress));
    NVN_CREATE_PROC(CommandBufferDrawElementsBaseVertex, void, (CommandBuffer*, DrawPrimitive::Enum, IndexType::Enum, int, BufferAddress, int));
    NVN_CREATE_PROC(CommandBufferDrawArraysInstanced, void, (CommandBuffer*, DrawPrimitive::Enum, int, int, int, int));
    NVN_CREATE_PROC(CommandBufferDrawElementsInstanced, void, (CommandBuffer*, DrawPrimitive::Enum, IndexType::Enum, int, BufferAddress, int, int, int));
    NVN_CREATE_PROC(CommandBufferDrawArraysIndirect, void, (CommandBuffer*, DrawPrimitive::Enum, BufferAddress));
    NVN_CREATE_PROC(CommandBufferDrawElementsIndirect, void, (CommandBuffer*, DrawPrimitive::Enum, IndexType::Enum, BufferAddress, BufferAddress));
    NVN_CREATE_PROC(CommandBufferMultiDrawArraysIndirectCount, void, (CommandBuffer*, DrawPrimitive::Enum, BufferAddress, BufferAddress, int, ptrdiff_t));
    NVN_CREATE_PROC(CommandBufferMultiDrawElementsIndirectCount, void, (CommandBuffer*, DrawPrimitive::Enum, IndexType::Enum, BufferAddress, BufferAddress, BufferAddress, int, ptrdiff_t));
    NVN_CREATE_PROC(CommandBufferClearColor, void, (CommandBuffer*, int, const float*, int));
    NVN_CREATE_PROC(CommandBufferClearColori, void, (CommandBuffer*, int, const int*, int));
    NVN_CREATE_PROC(CommandBufferClearColorui, void, (CommandBuffer*, int, const uint32_t*, int));
    NVN_CREATE_PROC(CommandBufferClearDepthStencil, void, (CommandBuffer*, float, bool, int, int));
    NVN_CREATE_PROC(CommandBufferDispatchCompute, void, (CommandBuffer*, int, int, int));
    NVN_CREATE_PROC(CommandBufferDispatchComputeIndirect, void, (CommandBuffer*, BufferAddress));
    NVN_CREATE_PROC(CommandBufferSetViewport, void, (CommandBuffer*, int, int, int, int));
    NVN_CREATE_PROC(CommandBufferSetViewports, void, (CommandBuffer*, int, int, const float*));
    NVN_CREATE_PROC(CommandBufferSetViewportSwizzles, void, (CommandBuffer*, int, int, const ViewportSwizzle*));
    NVN_CREATE_PROC(CommandBufferSetScissor, void, (CommandBuffer*, int, int, int, int));
    NVN_CREATE_PROC(CommandBufferSetScissors, void, (CommandBuffer*, int, int, const int*));
    NVN_CREATE_PROC(CommandBufferSetDepthRange, void, (CommandBuffer*, float, float));
    NVN_CREATE_PROC(CommandBufferSetDepthBounds, void, (CommandBuffer*, bool, float, float));
    NVN_CREATE_PROC(CommandBufferSetDepthRanges, void, (CommandBuffer*, int, int, const float*));
    NVN_CREATE_PROC(CommandBufferSetTiledCacheAction, void, (CommandBuffer*, TiledCacheAction::Enum));
    NVN_CREATE_PROC(CommandBufferSetTiledCacheTileSize, void, (CommandBuffer*, int, int));
    NVN_CREATE_PROC(CommandBufferSetStencilValueMask, void, (CommandBuffer*, Face::Enum, int));
    NVN_CREATE_PROC(CommandBufferSetStencilMask, void, (CommandBuffer*, Face::Enum, int));
    NVN_CREATE_PROC(CommandBufferSetStencilRef, void, (CommandBuffer*, Face::Enum, int));
    NVN_CREATE_PROC(CommandBufferSetBlendColor, void, (CommandBuffer*, const float*));
    NVN_CREATE_PROC(CommandBufferSetPointSize, void, (CommandBuffer*, float));
    NVN_CREATE_PROC(CommandBufferSetLineWidth, void, (CommandBuffer*, float));
    NVN_CREATE_PROC(CommandBufferSetPolygonOffsetClamp, void, (CommandBuffer*, float, float, float));
    NVN_CREATE_PROC(CommandBufferSetAlphaRef, void, (CommandBuffer*, float));
    NVN_CREATE_PROC(CommandBufferSetSampleMask, void, (CommandBuffer*, int));
    NVN_CREATE_PROC(CommandBufferSetRasterizerDiscard, void, (CommandBuffer*, bool));
    NVN_CREATE_PROC(CommandBufferSetDepthClamp, void, (CommandBuffer*, bool));
    NVN_CREATE_PROC(CommandBufferSetConservativeRasterEnable, void, (CommandBuffer*, bool));
    NVN_CREATE_PROC(CommandBufferSetConservativeRasterDilate, void, (CommandBuffer*, float));
    NVN_CREATE_PROC(CommandBufferSetSubpixelPrecisionBias, void, (CommandBuffer*, int, int));
    NVN_CREATE_PROC(CommandBufferCopyBufferToTexture, void, (CommandBuffer*, BufferAddress, const Texture*, const TextureView*, const CopyRegion*, int));
    NVN_CREATE_PROC(CommandBufferCopyTextureToBuffer, void, (CommandBuffer*, const Texture*, const TextureView*, const CopyRegion*, BufferAddress, int));
    NVN_CREATE_PROC(CommandBufferCopyTextureToTexture, void, (CommandBuffer*, const Texture*, const TextureView*, const CopyRegion*, const Texture*, const TextureView*, const CopyRegion*, int));
    NVN_CREATE_PROC(CommandBufferCopyBufferToBuffer, void, (CommandBuffer*, BufferAddress, BufferAddress, size_t, int));
    NVN_CREATE_PROC(CommandBufferClearBuffer, void, (CommandBuffer*, BufferAddress, size_t, uint32_t));
    NVN_CREATE_PROC(CommandBufferClearTexture, void, (CommandBuffer*, const Texture*, const TextureView*, const CopyRegion*, const float*, int));
    NVN_CREATE_PROC(CommandBufferClearTexturei, void, (CommandBuffer*, const Texture*, const TextureView*, const CopyRegion*, const int*, int));
    NVN_CREATE_PROC(CommandBufferClearTextureui, void, (CommandBuffer*, const Texture*, const TextureView*, const CopyRegion*, const uint32_t*, int));
    NVN_CREATE_PROC(CommandBufferUpdateUniformBuffer, void, (CommandBuffer*, BufferAddress, size_t, ptrdiff_t, size_t, const void*));
    NVN_CREATE_PROC(CommandBufferReportCounter, void, (CommandBuffer*, CounterType::Enum, BufferAddress));
    NVN_CREATE_PROC(CommandBufferResetCounter, void, (CommandBuffer*, CounterType::Enum));
    NVN_CREATE_PROC(CommandBufferReportValue, void, (CommandBuffer*, uint32_t, BufferAddress));
    NVN_CREATE_PROC(CommandBufferSetRenderEnable, void, (CommandBuffer*, bool));
    NVN_CREATE_PROC(CommandBufferSetRenderEnableConditional, void, (CommandBuffer*, ConditionalRenderMode::Enum, BufferAddress));
    NVN_CREATE_PROC(CommandBufferSetRenderTargets, void, (CommandBuffer*, int, const Texture* const*, const TextureView* const*, const Texture*, const TextureView*));
    NVN_CREATE_PROC(CommandBufferDiscardColor, void, (CommandBuffer*, int));
    NVN_CREATE_PROC(CommandBufferDiscardDepthStencil, void, (CommandBuffer*));
    NVN_CREATE_PROC(CommandBufferDownsample, void, (CommandBuffer*, const Texture*, const Texture*));
    NVN_CREATE_PROC(CommandBufferTiledDownsample, void, (CommandBuffer*, const Texture*, const Texture*));
    NVN_CREATE_PROC(CommandBufferBarrier, void, (CommandBuffer*, int));
    NVN_CREATE_PROC(CommandBufferWaitSync, void, (CommandBuffer*, const Sync*));
    NVN_CREATE_PROC(CommandBufferFenceSync, void, (CommandBuffer*, Sync*, SyncCondition::Enum, int));
    NVN_CREATE_PROC(CommandBufferSetTexturePool, void, (CommandBuffer*, const TexturePool*));
    NVN_CREATE_PROC(CommandBufferSetSamplerPool, void, (CommandBuffer*, const SamplerPool*));
    NVN_CREATE_PROC(CommandBufferSetShaderScratchMemory, void, (CommandBuffer*, const MemoryPool*, ptrdiff_t, size_t));
    NVN_CREATE_PROC(CommandBufferSaveZCullData, void, (CommandBuffer*, BufferAddress, size_t));
    NVN_CREATE_PROC(CommandBufferRestoreZCullData, void, (CommandBuffer*, BufferAddress, size_t));
    NVN_CREATE_PROC(CommandBufferSetCopyRowStride, void, (CommandBuffer*, ptrdiff_t));
    NVN_CREATE_PROC(CommandBufferSetCopyImageStride, void, (CommandBuffer*, ptrdiff_t));
    NVN_CREATE_PROC(CommandBufferGetCopyRowStride, ptrdiff_t, (const CommandBuffer*));
    NVN_CREATE_PROC(CommandBufferGetCopyImageStride, ptrdiff_t, (const CommandBuffer*));
    NVN_CREATE_PROC(CommandBufferDrawTexture, void, (CommandBuffer*, TextureHandle, const DrawTextureRegion*, const DrawTextureRegion*));
    NVN_CREATE_PROC(ProgramSetSubroutineLinkage, bool, (Program*, int, const SubroutineLinkageMapPtr*));
    NVN_CREATE_PROC(CommandBufferSetProgramSubroutines, void, (CommandBuffer*, Program*, ShaderStage::Enum, const int, const int, const int*));
    NVN_CREATE_PROC(CommandBufferBindCoverageModulationTable, void, (CommandBuffer*, const float*));
    NVN_CREATE_PROC(CommandBufferResolveDepthBuffer, void, (CommandBuffer*));
    NVN_CREATE_PROC(CommandBufferPushDebugGroup, void, (CommandBuffer*, const char*));
    NVN_CREATE_PROC(CommandBufferPopDebugGroup, void, (CommandBuffer*));
    NVN_CREATE_PROC(CommandBufferInsertDebugMarker, void, (CommandBuffer*, const char*));
    NVN_CREATE_PROC(CommandBufferGetMemoryCallback, CommandBufferMemoryCallback, (const CommandBuffer*));
    NVN_CREATE_PROC(CommandBufferGetMemoryCallbackData, void*, (const CommandBuffer*));
    NVN_CREATE_PROC(CommandBufferIsRecording, bool, (const CommandBuffer*));
    NVN_CREATE_PROC(SyncInitialize, bool, (Sync*, Device*));
    NVN_CREATE_PROC(SyncFinalize, void, (Sync*));
    NVN_CREATE_PROC(SyncSetDebugLabel, void, (Sync*, const char*));
    NVN_CREATE_PROC(QueueFenceSync, void, (Queue*, Sync*, SyncCondition::Enum, int));
    NVN_CREATE_PROC(SyncWait, SyncWaitResult::Enum, (const Sync*, uint64_t));
    NVN_CREATE_PROC(QueueWaitSync, bool, (Queue*, const Sync*));
}